ALTER TABLE retrieval_trace
    ADD COLUMN IF NOT EXISTS original_question TEXT,
    ADD COLUMN IF NOT EXISTS rewritten_query TEXT,
    ADD COLUMN IF NOT EXISTS query_rewrite_latency_ms BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS query_rewrite_status VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN IF NOT EXISTS generated_queries TEXT;

ALTER TABLE retrieval_trace_source
    ADD COLUMN IF NOT EXISTS vector_rank INTEGER,
    ADD COLUMN IF NOT EXISTS keyword_rank INTEGER,
    ADD COLUMN IF NOT EXISTS vector_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rrf_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS retrieval_source VARCHAR(40) NOT NULL DEFAULT 'VECTOR',
    ADD COLUMN IF NOT EXISTS rerank_rank INTEGER,
    ADD COLUMN IF NOT EXISTS rerank_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rerank_reason TEXT,
    ADD COLUMN IF NOT EXISTS original_token_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS compressed_token_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS compression_ratio DOUBLE PRECISION NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS compression_method VARCHAR(80) NOT NULL DEFAULT 'NONE';
